import {
  Tenant,
  Professional,
  Room,
  Equipment,
  Procedure,
  Client,
  Appointment,
  DailySummary,
  EvolutionRecord,
  InventoryItem,
} from "@/types";

export const mockTenant: Tenant = {
  id: "tenant-lumina-01",
  name: "Lumina Estúdio & Spa",
  slug: "lumina",
  phone: "11987654321",
  instagram: "@lumina.estudio",
  address: "Av. Paulista, 1800, Conjunto 42 — Bela Vista, São Paulo - SP",
  accentColor: "#C49B88",
};

export const mockRooms: Room[] = [
  {
    id: "room-cabelo",
    tenantId: "tenant-lumina-01",
    name: "Espaço Cabelo & Lavatórios",
    type: "bancada_cabelo",
    capacity: 2,
    status: "ativo",
    defaultProfessionalId: "pro-larissa",
    description: "Bancadas de corte/química e lavatórios reclináveis com massagem.",
  },
  {
    id: "room-unhas",
    tenantId: "tenant-lumina-01",
    name: "Bancada Nail Design",
    type: "mesa_unhas",
    capacity: 2,
    status: "ativo",
    defaultProfessionalId: "pro-jessica",
    description: "Mesas com aspirador de pó embutido e cabines LED UV duplas.",
  },
  {
    id: "room-lashes-brows",
    tenantId: "tenant-lumina-01",
    name: "Cabine Cílios & Sobrancelhas",
    type: "maca_cabine",
    capacity: 1,
    status: "ativo",
    defaultProfessionalId: "pro-bruna",
    description: "Maca articulada anatômica, luminária ring light e foco especial.",
  },
  {
    id: "room-estetica",
    tenantId: "tenant-lumina-01",
    name: "Cabine Estética Facial & Corporal",
    type: "maca_cabine",
    capacity: 1,
    status: "ativo",
    defaultProfessionalId: "pro-camila",
    description: "Maca aquecida, lupa cirúrgica e aparelhagem facial.",
  },
];

export const mockEquipments: Equipment[] = [
  {
    id: "equip-lavatorio",
    tenantId: "tenant-lumina-01",
    name: "Lavatório Spa Italiano",
    brandModel: "Maletti 2024",
    purchaseDate: "2024-02-10",
    purchasePrice: 6800.0,
  },
  {
    id: "equip-cabine-uv",
    tenantId: "tenant-lumina-01",
    name: "Cabine LED/UV Sun 5 Plus",
    brandModel: "SunUV 48W",
    serialNumber: "SN-SUV-9011",
    purchaseDate: "2024-06-15",
    purchasePrice: 280.0,
  },
  {
    id: "equip-led-facial",
    tenantId: "tenant-lumina-01",
    name: "Painel de Fototerapia LED",
    brandModel: "Cosmobr",
    serialNumber: "CSM-8824",
    purchaseDate: "2023-11-20",
    purchasePrice: 3400.0,
  },
];

const standardWorkingHours = [
  { dayOfWeek: 0, isOpen: false, startHour: "00:00", endHour: "00:00" }, // Dom
  { dayOfWeek: 1, isOpen: true, startHour: "09:00", endHour: "19:00", breakStart: "12:30", breakEnd: "13:30" }, // Seg
  { dayOfWeek: 2, isOpen: true, startHour: "09:00", endHour: "19:00", breakStart: "12:30", breakEnd: "13:30" }, // Ter
  { dayOfWeek: 3, isOpen: true, startHour: "09:00", endHour: "19:00", breakStart: "12:30", breakEnd: "13:30" }, // Qua
  { dayOfWeek: 4, isOpen: true, startHour: "09:00", endHour: "19:00", breakStart: "12:30", breakEnd: "13:30" }, // Qui
  { dayOfWeek: 5, isOpen: true, startHour: "09:00", endHour: "19:00", breakStart: "12:30", breakEnd: "13:30" }, // Sex
  { dayOfWeek: 6, isOpen: true, startHour: "08:30", endHour: "17:00" }, // Sáb
];

export const mockProfessionals: Professional[] = [
  {
    id: "pro-larissa",
    tenantId: "tenant-lumina-01",
    name: "Larissa Ferreira",
    role: "Hair Stylist & Colorista",
    phone: "11988881111",
    colorTag: "#C49B88",
    commissionPercentage: 50,
    workingHours: standardWorkingHours,
    qualifiedProcedureIds: ["proc-coloracao", "proc-corte-escova", "proc-mechas"],
  },
  {
    id: "pro-jessica",
    tenantId: "tenant-lumina-01",
    name: "Jéssica Alencar",
    role: "Nail Designer & Manicure",
    phone: "11988882222",
    colorTag: "#D4A373",
    commissionPercentage: 55,
    workingHours: standardWorkingHours,
    qualifiedProcedureIds: ["proc-alongamento-gel", "proc-manutencao-gel", "proc-manicure"],
  },
  {
    id: "pro-bruna",
    tenantId: "tenant-lumina-01",
    name: "Bruna Viana",
    role: "Lash & Brow Designer",
    phone: "11988883333",
    colorTag: "#9BA4B5",
    commissionPercentage: 60,
    workingHours: standardWorkingHours,
    qualifiedProcedureIds: ["proc-cilios-volume", "proc-manutencao-cilios", "proc-sobrancelha-henna", "proc-brow-lamination"],
  },
  {
    id: "pro-juliana",
    tenantId: "tenant-lumina-01",
    name: "Dra. Juliana Mendes",
    role: "Biomédica Esteta & Facial",
    phone: "11988884444",
    colorTag: "#B4A69B",
    commissionPercentage: 40,
    workingHours: standardWorkingHours,
    qualifiedProcedureIds: ["proc-limpeza", "proc-botox"],
  },
];

export const mockProcedures: Procedure[] = [
  // Cabelos
  {
    id: "proc-coloracao",
    tenantId: "tenant-lumina-01",
    name: "Coloração & Retoque de Raiz",
    category: "cabelo",
    price: 220,
    durationMinutes: 90,
    bufferMinutes: 15,
    processingTimeMinutes: 35, // 35 min de ação química da tinta
    requiredRoomId: "room-cabelo",
    preCareInstructions: "Vir com o cabelo seco e não lavado há pelo menos 24 horas.",
    postCareInstructions: "Usar shampoo acidificante sem sulfato para preservar a cor.",
    description: "Cobertura de fios brancos e uniformização da cor com tratamento de brilho.",
  },
  {
    id: "proc-corte-escova",
    tenantId: "tenant-lumina-01",
    name: "Corte Feminino & Escova Modelada",
    category: "cabelo",
    price: 160,
    durationMinutes: 60,
    bufferMinutes: 10,
    requiredRoomId: "room-cabelo",
    description: "Lavagem relaxante no lavatório spa, corte personalizado e escova com ondas.",
  },
  {
    id: "proc-mechas",
    tenantId: "tenant-lumina-01",
    name: "Mechas Iluminadas / Balayage",
    category: "cabelo",
    price: 480,
    durationMinutes: 180,
    bufferMinutes: 20,
    processingTimeMinutes: 50,
    requiredRoomId: "room-cabelo",
    preCareInstructions: "Fazer teste de mecha prévio e teste de sensibilidade ao descolorante.",
    postCareInstructions: "Cronograma capilar de nutrição e reconstrução pós-química.",
    description: "Efeito morena iluminada ou loiro dos sonhos com proteção plex contra danos.",
  },

  // Unhas
  {
    id: "proc-alongamento-gel",
    tenantId: "tenant-lumina-01",
    name: "Alongamento em Gel (Primeira Aplicação)",
    category: "unhas",
    price: 190,
    durationMinutes: 120,
    bufferMinutes: 15,
    requiredRoomId: "room-unhas",
    requiredEquipmentId: "equip-cabine-uv",
    description: "Extensão em molde russo ou fibra de vidro com acabamento natural e cutilagem russa.",
  },
  {
    id: "proc-manutencao-gel",
    tenantId: "tenant-lumina-01",
    name: "Manutenção de Alongamento em Gel",
    category: "unhas",
    price: 130,
    durationMinutes: 90,
    bufferMinutes: 10,
    requiredRoomId: "room-unhas",
    requiredEquipmentId: "equip-cabine-uv",
    description: "Nivelamento do crescimento, reforço estrutural, troca de formato e esmaltação.",
  },
  {
    id: "proc-manicure",
    tenantId: "tenant-lumina-01",
    name: "Manicure & Pedicure Completa",
    category: "unhas",
    price: 85,
    durationMinutes: 60,
    bufferMinutes: 10,
    requiredRoomId: "room-unhas",
    description: "Cutilagem suave, esfoliação, hidratação profunda e esmaltação tradicional.",
  },

  // Cílios
  {
    id: "proc-cilios-volume",
    tenantId: "tenant-lumina-01",
    name: "Extensão de Cílios — Volume Brasileiro",
    category: "cilios",
    price: 210,
    durationMinutes: 120,
    bufferMinutes: 15,
    requiredRoomId: "room-lashes-brows",
    preCareInstructions: "Vir sem rímel, maquiagem ou lentes de contato nos olhos.",
    postCareInstructions: "Não molhar por 24h. Pentear diariamente com a escovinha limpa.",
    description: "Técnica com fios em formato Y, proporcionando densidade com leveza e retenção duradoura.",
  },
  {
    id: "proc-manutencao-cilios",
    tenantId: "tenant-lumina-01",
    name: "Manutenção de Cílios (até 21 dias)",
    category: "cilios",
    price: 120,
    durationMinutes: 75,
    bufferMinutes: 10,
    requiredRoomId: "room-lashes-brows",
    preCareInstructions: "Estar com pelo menos 40% dos fios preservados.",
    postCareInstructions: "Higienizar com espuma própria para extensão de cílios.",
    description: "Remoção dos fios crescidos e preenchimento completo para restaurar o olhar.",
  },

  // Sobrancelhas
  {
    id: "proc-sobrancelha-henna",
    tenantId: "tenant-lumina-01",
    name: "Design Estratégico com Henna",
    category: "sobrancelhas",
    price: 65,
    durationMinutes: 45,
    bufferMinutes: 10,
    requiredRoomId: "room-lashes-brows",
    preCareInstructions: "Evitar uso de ácidos esfoliantes na testa antes da sessão.",
    postCareInstructions: "Não lavar a região com água quente nem esfregar sabonete nas primeiras 12h.",
    description: "Mapeamento facial personalizado, alinhamento com pinça e aplicação de henna orgânica.",
  },
  {
    id: "proc-brow-lamination",
    tenantId: "tenant-lumina-01",
    name: "Brow Lamination + Nutrição",
    category: "sobrancelhas",
    price: 140,
    durationMinutes: 60,
    bufferMinutes: 10,
    requiredRoomId: "room-lashes-brows",
    description: "Alinhamento e efeito volumoso nos fios naturais com hidratação de queratina.",
  },

  // Facial
  {
    id: "proc-limpeza",
    tenantId: "tenant-lumina-01",
    name: "Limpeza de Pele Profunda + LED",
    category: "facial",
    price: 180,
    durationMinutes: 60,
    bufferMinutes: 15,
    requiredRoomId: "room-estetica",
    requiredEquipmentId: "equip-led-facial",
    description: "Extração de impurezas, vapor de ozônio, hidratação e fototerapia bactericida.",
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: "inv-gel-volia",
    tenantId: "tenant-lumina-01",
    name: "Gel Construtor Vòlia Classic Nude 24g",
    brand: "Vòlia Cosméticos",
    category: "unhas",
    usageType: "insumo_bancada",
    currentStock: 4,
    unit: "potes",
    minStockAlert: 2,
    lastPurchaseDate: "2026-09-12",
    lastPurchasePrice: 78.90,
    supplier: "Distribuidora Vòlia SP",
    notes: "Rende em média 15 manutenções (custo de ~R$ 5,26 por cliente).",
  },
  {
    id: "inv-cola-sobelle",
    tenantId: "tenant-lumina-01",
    name: "Cola de Cílios Sobelle Master Elite 3ml",
    brand: "Sobelle Brasil",
    category: "cilios",
    usageType: "insumo_bancada",
    currentStock: 2,
    unit: "frascos",
    minStockAlert: 2, // ALERTA ATIVO
    lastPurchaseDate: "2026-09-05",
    lastPurchasePrice: 145.00,
    supplier: "Lash Master Distribuidora",
    notes: "Umidade ideal 45% a 65%. Tempo de secagem 0.5s.",
  },
  {
    id: "inv-cilios-nagaraku",
    tenantId: "tenant-lumina-01",
    name: "Caixa Cílios Nagaraku Volume Brasileiro 0.07D",
    brand: "Nagaraku",
    category: "cilios",
    usageType: "insumo_bancada",
    currentStock: 8,
    unit: "caixas",
    minStockAlert: 4,
    lastPurchaseDate: "2026-09-10",
    lastPurchasePrice: 38.50,
    supplier: "Lash Shop Brasil",
    notes: "Mix de tamanhos 8mm a 14mm.",
  },
  {
    id: "inv-tintura-majirel",
    tenantId: "tenant-lumina-01",
    name: "Coloração Majirel 6.0 Louro Escuro 50g",
    brand: "L'Oréal Professionnel",
    category: "cabelo",
    usageType: "insumo_bancada",
    currentStock: 6,
    unit: "tubos",
    minStockAlert: 3,
    lastPurchaseDate: "2026-09-15",
    lastPurchasePrice: 42.00,
    supplier: "L'Oréal Pro Direct",
    notes: "A tinta mais usada para retoque de fios brancos.",
  },
  {
    id: "inv-ox-20",
    tenantId: "tenant-lumina-01",
    name: "Oxidante Creme 20 Volumes 900ml",
    brand: "L'Oréal Professionnel",
    category: "cabelo",
    usageType: "insumo_bancada",
    currentStock: 3,
    unit: "frascos",
    minStockAlert: 2,
    lastPurchaseDate: "2026-09-15",
    lastPurchasePrice: 35.00,
    supplier: "L'Oréal Pro Direct",
  },
  {
    id: "inv-oleo-sebastian",
    tenantId: "tenant-lumina-01",
    name: "Óleo Reparador Dark Oil Sebastian 95ml",
    brand: "Sebastian Professional",
    category: "cabelo",
    usageType: "revenda_homecare",
    currentStock: 5,
    unit: "unidades",
    minStockAlert: 2,
    lastPurchaseDate: "2026-09-08",
    lastPurchasePrice: 110.00,
    resalePrice: 195.00, // Margem de R$ 85,00
    supplier: "Wella / Sebastian SP",
    notes: "Campeão de vendas no checkout do salão.",
  },
  {
    id: "inv-serum-cilios",
    tenantId: "tenant-lumina-01",
    name: "Sérum Nutritivo para Cílios & Sobrancelhas 10ml",
    brand: "Lumina Home Care",
    category: "cilios",
    usageType: "revenda_homecare",
    currentStock: 4,
    unit: "unidades",
    minStockAlert: 2,
    lastPurchaseDate: "2026-09-01",
    lastPurchasePrice: 39.00,
    resalePrice: 89.00,
    supplier: "Laboratório Farmacêutico",
    notes: "Ideal para indicar após remoção ou laminação.",
  },
  {
    id: "inv-luvas-nitrilo",
    tenantId: "tenant-lumina-01",
    name: "Luvas de Nitrilo Rosa sem Pó (Caixa 100un)",
    brand: "Unigloves",
    category: "descartaveis",
    usageType: "insumo_bancada",
    currentStock: 3,
    unit: "caixas",
    minStockAlert: 2,
    lastPurchaseDate: "2026-09-14",
    lastPurchasePrice: 48.00,
    supplier: "Dental & Estética Sul",
  },
];

export const mockClients: Client[] = [
  {
    id: "cli-beatriz",
    tenantId: "tenant-lumina-01",
    name: "Beatriz Nogueira",
    phone: "11982345678",
    email: "beatriz.n@email.com",
    birthDate: "1988-11-22",
    notes: "Faz extensão de cílios rigorosamente a cada 20 dias. Gosta de chá gelado na recepção.",
    tags: ["Cílios VIP", "Manutenção Frequente"],
    lastAppointmentAt: "2026-09-01",
    totalAppointments: 6,
    totalSpent: 980,
    technicalProfile: {
      lashMapping: "Volume Brasileiro, Fios Y 0.07, Curvatura D, tamanhos 10 a 13mm (Efeito Boneca)",
      allergies: "Sensível a colas com odor forte. Usar ventilador portátil para secagem.",
    },
  },
  {
    id: "cli-mariana",
    tenantId: "tenant-lumina-01",
    name: "Mariana Alencar",
    phone: "11991234567",
    email: "mariana.alencar@email.com",
    birthDate: "1992-05-14",
    notes: "Faz unha em gel e sobrancelha com henna no mesmo dia.",
    tags: ["Unhas em Gel", "Sobrancelha"],
    lastAppointmentAt: "2026-09-05",
    totalAppointments: 8,
    totalSpent: 1240,
    technicalProfile: {
      nailShape: "Formato Amendoada clássica, Gel Vòlia Classic Nude, Top Coat fosco",
      browHenna: "Tom Castanho Médio, tempo de ação exato de 7 minutos para não escurecer.",
    },
  },
  {
    id: "cli-carolina",
    tenantId: "tenant-lumina-01",
    name: "Carolina Vasconcelos",
    phone: "11973456789",
    birthDate: "1995-03-08",
    notes: "Retoca raiz de 35 em 35 dias. Cabelo com tendência ao ressecamento.",
    tags: ["Colorista VIP", "Corte & Escova"],
    lastAppointmentAt: "2026-08-15",
    totalAppointments: 5,
    totalSpent: 1650,
    technicalProfile: {
      hairFormula: "Raiz: Majirel 6.0 (35g) + 6.1 (15g) com OX 20 vol (75g). Lavar com Sebastian Dark Oil.",
      allergies: "Couro cabeludo sensível a descolorante direto.",
    },
  },
  {
    id: "cli-renata",
    tenantId: "tenant-lumina-01",
    name: "Renata Silveira",
    phone: "11964567890",
    birthDate: "1990-09-30",
    notes: "Primeiro agendamento pelo Instagram para limpeza de pele e sobrancelha.",
    tags: ["Novo Contato", "Instagram"],
    totalAppointments: 1,
    totalSpent: 180,
  },
];

// Data atual de simulação: 2026-09-20
export const mockAppointments: Appointment[] = [
  {
    id: "app-1",
    tenantId: "tenant-lumina-01",
    clientId: "cli-carolina",
    clientName: "Carolina Vasconcelos",
    clientPhone: "11973456789",
    professionalId: "pro-larissa",
    professionalName: "Larissa Ferreira",
    procedureId: "proc-coloracao",
    procedureName: "Coloração & Retoque de Raiz",
    roomId: "room-cabelo",
    roomName: "Espaço Cabelo & Lavatórios",
    date: "2026-09-20",
    startTime: "09:00",
    endTime: "10:30",
    durationMinutes: 90,
    bufferMinutes: 15,
    price: 220,
    status: "concluido",
    paid: true,
    paymentMethod: "pix",
    notes: "Fórmula 6.0 + 6.1 aplicada com perfeição. Brilho excelente.",
    createdAt: "2026-09-15T10:00:00Z",
  },
  {
    id: "app-2",
    tenantId: "tenant-lumina-01",
    clientId: "cli-mariana",
    clientName: "Mariana Alencar",
    clientPhone: "11991234567",
    professionalId: "pro-jessica",
    professionalName: "Jéssica Alencar",
    procedureId: "proc-manutencao-gel",
    procedureName: "Manutenção de Alongamento em Gel",
    roomId: "room-unhas",
    roomName: "Bancada Nail Design",
    equipmentId: "equip-cabine-uv",
    equipmentName: "Cabine LED/UV Sun 5 Plus",
    date: "2026-09-20",
    startTime: "10:30",
    endTime: "12:00",
    durationMinutes: 90,
    bufferMinutes: 10,
    price: 130,
    status: "em_atendimento",
    paid: true,
    paymentMethod: "cartao_credito",
    notes: "Manutenção amendoada com Gel Vòlia Classic Nude.",
    createdAt: "2026-09-16T14:30:00Z",
  },
  {
    id: "app-3",
    tenantId: "tenant-lumina-01",
    clientId: "cli-beatriz",
    clientName: "Beatriz Nogueira",
    clientPhone: "11982345678",
    professionalId: "pro-bruna",
    professionalName: "Bruna Viana",
    procedureId: "proc-manutencao-cilios",
    procedureName: "Manutenção de Cílios (até 21 dias)",
    roomId: "room-lashes-brows",
    roomName: "Cabine Cílios & Sobrancelhas",
    date: "2026-09-20",
    startTime: "13:30",
    endTime: "14:45",
    durationMinutes: 75,
    bufferMinutes: 10,
    price: 120,
    status: "confirmado",
    paid: false,
    notes: "Confirmou presença via WhatsApp. Fios Y preservados.",
    createdAt: "2026-09-17T11:20:00Z",
  },
  {
    id: "app-4",
    tenantId: "tenant-lumina-01",
    clientId: "cli-renata",
    clientName: "Renata Silveira",
    clientPhone: "11964567890",
    professionalId: "pro-bruna",
    professionalName: "Bruna Viana",
    procedureId: "proc-sobrancelha-henna",
    procedureName: "Design Estratégico com Henna",
    roomId: "room-lashes-brows",
    roomName: "Cabine Cílios & Sobrancelhas",
    date: "2026-09-20",
    startTime: "15:00",
    endTime: "15:45",
    durationMinutes: 45,
    bufferMinutes: 10,
    price: 65,
    status: "agendado",
    paid: false,
    notes: "Primeiro atendimento. Enviar mensagem de boas-vindas.",
    createdAt: "2026-09-18T09:10:00Z",
  },
];

export const mockDailySummary: DailySummary = {
  date: "2026-09-20",
  tenantId: "tenant-lumina-01",
  totalAppointments: 4,
  totalRevenue: 535,
  completedCount: 1,
  canceledCount: 0,
  missedCount: 0,
  pendingPaymentCount: 2,
};

export const mockEvolutionRecords: EvolutionRecord[] = [
  {
    id: "evo-1",
    tenantId: "tenant-lumina-01",
    clientId: "cli-beatriz",
    date: "2026-09-01",
    procedureName: "Extensão de Cílios — Volume Brasileiro",
    professionalName: "Bruna Viana",
    observations: "Excelente retenção. Usada cola Sobelle Master Elite em 55% de umidade.",
    parametersUsed: "Mapping Boneca 10-13mm, Curvatura D",
  },
];
